### PR TITLE
Fix 604

### LINKED ISSUE #604: Broken error message for missing required property
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

v5.5.0

### Stopped working in version

v5.6.0

### Node.js version

18.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

ventura

### 💥 Regression Report

The error message is now reporting "NaN" instead of the property name for the latest fast-json-stringify release.

### Steps to Reproduce

Run the following in this repo:

```
'use strict'

const assert = require('assert')
const fjs = require('./index')
const schema = {
  type: 'object',
  properties: {
    fullName: { type: 'string' },
    phone: { type: 'number' }
  }
}

const input = {
  fullName: 'Jone',
  phone: 'phone'
}

const render = fjs(schema)

try {
  render(input)
} catch (err) {
  assert.equal(err.message, 'The value "phone" cannot be converted to a number.')
}
```

### Expected Behavior

The correct property name is listed in the error message

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #604 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by ivan-tymoshenko — APPROVED** [review]
lgtm

File: lib/serializer.js [hunk 1]
```diff
@@ -50,17 +50,14 @@ module.exports = class Serializer {
...
   asNumber (i) {
-    if (typeof i !== 'number') {
-      i = Number(i)
-    }
-    // NaN !== NaN
-    if (i !== i) { // eslint-disable-line no-self-compare
+    const num = Number(i)
+    if (Number.isNaN(num)) {
       throw new Error(`The value "${i}" cannot be converted to a number.`)
+    } else if (!Number.isFinite(num)) {
```
Comment (ivan-tymoshenko) [inline lib/serializer.js:56]: @Uzlopak I will approve it because I'm not if it makes any perf difference with `i === Infinity || i === -Infinity`, but if it does, feel free to open a new PR.

**Comment by Uzlopak** [comment]
It would have been this: 

```js
asNumber (i) {
    const num = i
    if (typeof i !== 'number') {
      i = Number(i)
    }
    // NaN !== NaN
    if (i !== i) { // eslint-disable-line no-self-compare
      throw new Error(`The value "${num}" cannot be converted to a number.`)
    }
    if (i === Infinity || i === -Infinity) {
      return 'null'
    }
    return '' + i
  }

```
