### PR TITLE
fix: reset json pointer in merged allOf schema

### LINKED ISSUE #481: Ajv validation inside allOf
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

There is a fastify issue https://github.com/fastify/fastify/issues/4092
I reduced the test example.

```js
test('anyOf inside allOf', (t) => {
  t.plan(1)

  const schema = {
    anyOf: [
      {
        type: 'object',
        allOf: [
          {
            properties: {
              a: {
                anyOf: [
                  { const: 'A1' },
                  { const: 'A2' }
                ]
              }
            }
          },
          {
            properties: {
              b: { const: 'B' }
            }
          }
        ]
      }
    ]
  }

  const object = { a: 'A1', b: 'B' }
  const stringify = build(schema)
  const output = stringify(object)

  t.equal(output, JSON.stringify(object))
})
```

I'm working on that.

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fix #481
Fix https://github.com/fastify/fastify/issues/4092

#480 sets merged schema as a location, but doesn't set json pointer to the root of this merged schema.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -493,6 +493,7 @@ function mergeAllOfSchema (location, schema, mergedSchema) {
   mergedSchema.$id = `merged_${randomUUID()}`
   ajvInstance.addSchema(mergedSchema)
   location.schemaId = mergedSchema.$id
+  location.jsonPointer = '#'
```
Comment (climba03003) [inline index.js:496]: Will it be problem of deeply nested schema?

Comment (ivan-tymoshenko) [reply index.js:496]: It should work with nested schemas. Can you provide an example of what you mean?

Comment (climba03003) [reply index.js:496]: I get my answer when I create the example.
Here comes one problem related to previous fix.

Recursive `$ref` will be a problem when using `allOf`.

```js
{
  $id: 'base',
  anyOf: [
    {
      type: 'object',
      allOf: [
        {
          properties: {
            a: {
              anyOf: [
                { const: 'A1' },
                { const: 'A2' }
              ]
            }
          }
        },
        {
          properties: {
            b: { const: 'B' }
          }
        },
        {
          properties: {
            c: {
              oneOf: [
                { $ref: 'base' },
                { type: 'null' }
              ]
            }
          }
        }
      ]
    }
  ]
}
```

**Review by climba03003 — APPROVED** [review]
LGTM.

File: index.js (hunk 1 above)
Comment (ivan-tymoshenko) [reply index.js:496]: I guess we can fix this. But there are some other problems with merging schemas that we should also. We can't use deepMerge for merging. I was trying to make it better #453, but it's not enough. We can check how [json-schema-merge-allof](https://www.npmjs.com/package/json-schema-merge-allof) works.

In general, we have some places where we have troubles (if/then, oneOf, anyOf, allOf, type array), bc json schema format designed for validation and described input types and we use json schema for serialization and ask people to describe output types.

Comment (climba03003) [reply index.js:496]: I think it worth an issue for discussion.

**Review by mcollina — APPROVED** [review]
lgtm
