### PR TITLE
fix: throw an error if cannot convert value to number

### LINKED ISSUE #431: Ignore invalid number value
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Now, if number/integer value is invalid, it will be skipped. Is that expected behavior?

```js
const stringify1 = fastJson({ type: 'object', properties: { a: { type: 'number' }} })
const stringify2 = fastJson({ type: 'object', properties: { a: { type: 'number', nullable: true }} })

stringify1({ a: 'invalid' }) // {}
stringify2({ a: 'invalid' }) // {}
```

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fixed #431

### CODE REVIEW

**Comment by ivan-tymoshenko** [comment]
Снимок экрана 2022-05-27 в 17 53 58

File: index.js [hunk 1]
```diff
@@ -86,10 +86,15 @@ class Serializer {
     if (typeof i === 'bigint') {
       return i.toString()
     } else if (Number.isInteger(i)) {
-      return this.asNumber(i)
+      return '' + i
     } else {
       /* eslint no-undef: "off" */
-      return this.asNumber(this.parseInteger(i))
+      const integer = this.parseInteger(i)
+      if (isNaN(integer)) {
```
Comment (Fdawgs) [inline index.js:93]: Would changing this to `Number.isNaN()` impact performance at all? I know `Global.isNaN()` attempts type coercion.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Fdawgs — APPROVED** [review]
